package io.butler.bet.intelligence;

import io.butler.bet.data.Database;
import io.butler.bet.data.PlayerRepository;
import io.butler.bet.data.PlayerWeekProductionCoverageRepository;
import io.butler.bet.data.PlayerWeekProductionRepository;
import io.butler.bet.domain.PlayerWeekProduction;
import io.butler.bet.domain.PlayerWeekProductionCoverage;
import io.butler.bet.domain.RawScoringProduction;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.sql.SQLException;
import java.time.Duration;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Imports raw nflverse regular-season week production using exact GSIS-to-Sleeper identity mapping. */
public final class NflversePlayerWeekProductionImporter {
    public static final String SOURCE=NflversePlayerSeasonProductionImporter.SOURCE;
    private static final Set<String> EXTENDED_COLUMNS=Set.of("passing_2pt_conversions","carries","rushing_2pt_conversions","receiving_2pt_conversions","fumble_recovery_tds","special_teams_tds");
    private final PlayerRepository players;private final PlayerWeekProductionRepository production;private final PlayerWeekProductionCoverageRepository coverage;private final HttpClient http;
    public NflversePlayerWeekProductionImporter(Database db){this(db,HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(20)).followRedirects(HttpClient.Redirect.NORMAL).build());}
    NflversePlayerWeekProductionImporter(Database db,HttpClient http){Objects.requireNonNull(db,"database must not be null");players=new PlayerRepository(db);production=new PlayerWeekProductionRepository(db);coverage=new PlayerWeekProductionCoverageRepository(db);this.http=Objects.requireNonNull(http,"http must not be null");}
    public ImportResult refresh(int s)throws IOException,InterruptedException,SQLException{return fetchAndProcess(s,true);}public ImportResult preview(int s)throws IOException,InterruptedException,SQLException{return fetchAndProcess(s,false);}
    public ImportResult importCsv(int s,String stats,String ids,LocalDate d)throws SQLException{return processCsv(s,stats,ids,d,true);}public ImportResult previewCsv(int s,String stats,String ids,LocalDate d)throws SQLException{return processCsv(s,stats,ids,d,false);}
    private ImportResult fetchAndProcess(int season,boolean persist)throws IOException,InterruptedException,SQLException{requireSeason(season);return processCsv(season,download(statsUri(season),"nflverse weekly player stats for "+season),download(NflversePlayerSeasonProductionImporter.PLAYER_IDS_URI,"fantasy player id crosswalk"),LocalDate.now(),persist);}
    private ImportResult processCsv(int season,String statsCsv,String idsCsv,LocalDate asOf,boolean persist)throws SQLException{
        requireSeason(season);Objects.requireNonNull(asOf,"asOfDate must not be null");List<Map<String,String>>rows=Csv.parse(requireText(statsCsv,"statsCsv")),ids=Csv.parse(requireText(idsCsv,"idsCsv"));if(rows.isEmpty())throw new IllegalArgumentException("nflverse weekly stats contain no data rows");if(ids.isEmpty())throw new IllegalArgumentException("player-id crosswalk contains no data rows");int rawSchema=detectRawScoringSchema(rows.getFirst());
        Map<String,String> sleeperByGsis=buildCrosswalk(ids),localBySleeper=buildLocalPlayerIndex();List<String>identityCovered=identityCoveredPlayers(sleeperByGsis,localBySleeper);Map<PlayerWeekKey,ProviderProduction>mapped=new LinkedHashMap<>();List<UnmatchedProviderRow>unmatched=new ArrayList<>();Map<Integer,Integer>providerByWeek=new LinkedHashMap<>(),unmatchedByWeek=new LinkedHashMap<>();int requested=0,regular=0;
        for(Map<String,String>row:rows){int rs=parseNonNegativeInt(required(row,"season"),"season","provider row");if(rs!=season)continue;requested++;if(!"REG".equalsIgnoreCase(requireText(required(row,"season_type"),"season_type").trim()))continue;regular++;int week=parsePositiveInt(required(row,"week"),"week","provider row");providerByWeek.merge(week,1,Integer::sum);String gsis=normalizeId(required(row,"player_id"));if(gsis==null)throw new IllegalArgumentException("blank nflverse player_id for season "+season+" week "+week);String sleeper=sleeperByGsis.get(gsis);if(sleeper==null){unmatched.add(new UnmatchedProviderRow(gsis,null,week,"No GSIS-to-Sleeper mapping"));unmatchedByWeek.merge(week,1,Integer::sum);continue;}String local=localBySleeper.get(sleeper);if(local==null){unmatched.add(new UnmatchedProviderRow(gsis,sleeper,week,"No local player for Sleeper id"));unmatchedByWeek.merge(week,1,Integer::sum);continue;}
            ProviderProduction p=new ProviderProduction(local,gsis,sleeper,week,parseSignedInt(value(row,"passing_yards"),"passing_yards",gsis),parseNonNegativeInt(value(row,"passing_tds"),"passing_tds",gsis),parseNonNegativeInt(value(row,"passing_interceptions"),"passing_interceptions",gsis),parseSignedInt(value(row,"rushing_yards"),"rushing_yards",gsis),parseNonNegativeInt(value(row,"rushing_tds"),"rushing_tds",gsis),parseNonNegativeInt(value(row,"receptions"),"receptions",gsis),parseSignedInt(value(row,"receiving_yards"),"receiving_yards",gsis),parseNonNegativeInt(value(row,"receiving_tds"),"receiving_tds",gsis),parseNonNegativeInt(value(row,"sack_fumbles_lost"),"sack_fumbles_lost",gsis)+parseNonNegativeInt(value(row,"rushing_fumbles_lost"),"rushing_fumbles_lost",gsis)+parseNonNegativeInt(value(row,"receiving_fumbles_lost"),"receiving_fumbles_lost",gsis),rawSchema==2?parseNonNegativeInt(value(row,"passing_2pt_conversions"),"passing_2pt_conversions",gsis):0,rawSchema==2?parseNonNegativeInt(value(row,"carries"),"carries",gsis):0,rawSchema==2?parseNonNegativeInt(value(row,"rushing_2pt_conversions"),"rushing_2pt_conversions",gsis):0,rawSchema==2?parseNonNegativeInt(value(row,"receiving_2pt_conversions"),"receiving_2pt_conversions",gsis):0,rawSchema==2?parseNonNegativeInt(value(row,"fumble_recovery_tds"),"fumble_recovery_tds",gsis):0,rawSchema==2?parseNonNegativeInt(value(row,"special_teams_tds"),"special_teams_tds",gsis):0,rawSchema);
            PlayerWeekKey key=new PlayerWeekKey(local,week);ProviderProduction old=mapped.putIfAbsent(key,p);if(old!=null&&!old.equals(p))throw new IllegalArgumentException("ambiguous nflverse weekly production for player "+local+" week "+week);
        }
        if(requested==0)throw new IllegalArgumentException("nflverse weekly stats contain no rows for season: "+season);if(regular==0)throw new IllegalArgumentException("nflverse weekly stats contain no REG rows for season: "+season);Map<Integer,Integer>matchedByWeek=new LinkedHashMap<>();for(ProviderProduction p:mapped.values())matchedByWeek.merge(p.week(),1,Integer::sum);int written=0;
        if(persist){coverage.deleteBySeasonAsOf(season,SOURCE,asOf);for(ProviderProduction p:mapped.values()){PlayerWeekProduction snap=p.rawSchema()==RawScoringProduction.EXTENDED_SCHEMA_VERSION?PlayerWeekProduction.createExactScoringV2(p.localPlayerId(),season,p.week(),p.passingYards(),p.passingTouchdowns(),p.interceptions(),p.rushingYards(),p.rushingTouchdowns(),p.receptions(),p.receivingYards(),p.receivingTouchdowns(),p.fumblesLost(),p.passingTwoPointConversions(),p.rushingAttempts(),p.rushingTwoPointConversions(),p.receivingTwoPointConversions(),p.fumbleRecoveryTouchdowns(),p.specialTeamsTouchdowns(),SOURCE,asOf):PlayerWeekProduction.create(p.localPlayerId(),season,p.week(),p.passingYards(),p.passingTouchdowns(),p.interceptions(),p.rushingYards(),p.rushingTouchdowns(),p.receptions(),p.receivingYards(),p.receivingTouchdowns(),p.fumblesLost(),SOURCE,asOf);production.save(snap);written++;}for(var e:providerByWeek.entrySet()){int w=e.getKey();coverage.replace(new PlayerWeekProductionCoverage(season,w,SOURCE,statsUri(season),asOf,e.getValue(),matchedByWeek.getOrDefault(w,0),unmatchedByWeek.getOrDefault(w,0),identityCovered));}}
        return new ImportResult(season,asOf,persist,rows.size(),requested,regular,mapped.size(),unmatched.size(),written,List.copyOf(unmatched));
    }
    private static int detectRawScoringSchema(Map<String,String>row){long n=EXTENDED_COLUMNS.stream().filter(row::containsKey).count();if(n==0)return 1;if(n==EXTENDED_COLUMNS.size())return 2;throw new IllegalArgumentException("partial nflverse extended scoring schema; expected all columns "+EXTENDED_COLUMNS);}
    public static URI statsUri(int season){requireSeason(season);return URI.create("https://github.com/nflverse/nflverse-data/releases/download/stats_player/stats_player_week_"+season+".csv");}
    private Map<String,String>buildLocalPlayerIndex()throws SQLException{Map<String,String>r=new LinkedHashMap<>();for(var p:players.findAll()){String s=normalizeId(p.getExternalId());if(s==null)continue;String old=r.putIfAbsent(s,p.getId());if(old!=null&&!old.equals(p.getId()))throw new IllegalArgumentException("ambiguous local players for Sleeper id: "+s);}return r;}
    private static List<String>identityCoveredPlayers(Map<String,String>a,Map<String,String>b){Set<String>s=new HashSet<>(a.values());return b.entrySet().stream().filter(e->s.contains(e.getKey())).map(Map.Entry::getValue).sorted().toList();}
    private static Map<String,String>buildCrosswalk(List<Map<String,String>>rows){Map<String,String>r=new LinkedHashMap<>();for(Map<String,String>row:rows){String g=normalizeId(row.get("gsis_id")),s=normalizeId(row.get("sleeper_id"));if(g==null||s==null)continue;String old=r.putIfAbsent(g,s);if(old!=null&&!old.equals(s))throw new IllegalArgumentException("ambiguous GSIS-to-Sleeper mapping for GSIS id: "+g);}if(r.isEmpty())throw new IllegalArgumentException("player-id crosswalk contains no GSIS-to-Sleeper mappings");return r;}
    private String download(URI uri,String desc)throws IOException,InterruptedException{HttpResponse<String>r=http.send(HttpRequest.newBuilder(uri).timeout(Duration.ofSeconds(60)).header("User-Agent","Butler-FF/0.1").GET().build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()!=200)throw new IOException(desc+" unavailable (HTTP "+r.statusCode()+"): "+uri);return r.body();}
    private static String required(Map<String,String>r,String c){if(!r.containsKey(c))throw new IllegalArgumentException("missing nflverse column: "+c);return r.get(c);}private static String value(Map<String,String>r,String c){if(!r.containsKey(c))throw new IllegalArgumentException("missing nflverse column: "+c);String v=r.get(c);return v==null||v.isBlank()||v.equalsIgnoreCase("NA")?"0":v;}private static int parsePositiveInt(String t,String f,String id){int p=parseIntegralInt(t,f,id);if(p<=0)throw new IllegalArgumentException("invalid nflverse "+f+" for "+id+": "+t);return p;}private static int parseNonNegativeInt(String t,String f,String id){int p=parseIntegralInt(t,f,id);if(p<0)throw new IllegalArgumentException("invalid nflverse "+f+" for "+id+": "+t);return p;}private static int parseSignedInt(String t,String f,String id){return parseIntegralInt(t,f,id);}private static int parseIntegralInt(String t,String f,String id){try{double p=Double.parseDouble(t.trim());if(!Double.isFinite(p)||p!=Math.rint(p)||p<Integer.MIN_VALUE||p>Integer.MAX_VALUE)throw new NumberFormatException();return(int)p;}catch(RuntimeException e){throw new IllegalArgumentException("invalid nflverse "+f+" for "+id+": "+t,e);}}
    private static String normalizeId(String v){if(v==null||v.isBlank()||v.equalsIgnoreCase("NA"))return null;String n=v.trim();if(n.matches("[0-9]+\\.0"))n=n.substring(0,n.length()-2);return n;}private static void requireSeason(int s){if(s<1999||s>2100)throw new IllegalArgumentException("season must be between 1999 and 2100");}private static String requireText(String v,String f){if(v==null||v.isBlank())throw new IllegalArgumentException(f+" must not be blank");return v;}
    public record ImportResult(int season,LocalDate asOfDate,boolean persisted,int providerRows,int requestedSeasonRows,int regularSeasonRows,int matchedPlayerWeeks,int unmatchedProviderRows,int snapshotsWritten,List<UnmatchedProviderRow>unmatched){public ImportResult{Objects.requireNonNull(asOfDate,"asOfDate must not be null");unmatched=List.copyOf(Objects.requireNonNull(unmatched,"unmatched must not be null"));}}
    public record UnmatchedProviderRow(String gsisId,String sleeperId,int week,String reason){}private record PlayerWeekKey(String playerId,int week){}private record ProviderProduction(String localPlayerId,String gsisId,String sleeperId,int week,int passingYards,int passingTouchdowns,int interceptions,int rushingYards,int rushingTouchdowns,int receptions,int receivingYards,int receivingTouchdowns,int fumblesLost,int passingTwoPointConversions,int rushingAttempts,int rushingTwoPointConversions,int receivingTwoPointConversions,int fumbleRecoveryTouchdowns,int specialTeamsTouchdowns,int rawSchema){}
    private static final class Csv{private Csv(){}static List<Map<String,String>>parse(String csv){List<List<String>>rows=rows(csv);if(rows.isEmpty())return List.of();List<String>h=rows.getFirst();List<Map<String,String>>out=new ArrayList<>();for(int i=1;i<rows.size();i++){List<String>v=rows.get(i);if(v.size()==1&&v.getFirst().isBlank())continue;Map<String,String>r=new LinkedHashMap<>();for(int j=0;j<h.size();j++)r.put(h.get(j).trim(),j<v.size()?v.get(j):"");out.add(r);}return out;}private static List<List<String>>rows(String csv){List<List<String>>out=new ArrayList<>();List<String>row=new ArrayList<>();StringBuilder cell=new StringBuilder();boolean quoted=false;for(int i=0;i<csv.length();i++){char c=csv.charAt(i);if(c=='"'){if(quoted&&i+1<csv.length()&&csv.charAt(i+1)=='"'){cell.append('"');i++;}else quoted=!quoted;}else if(c==','&&!quoted){row.add(cell.toString());cell.setLength(0);}else if((c=='\n'||c=='\r')&&!quoted){if(c=='\r'&&i+1<csv.length()&&csv.charAt(i+1)=='\n')i++;row.add(cell.toString());cell.setLength(0);out.add(row);row=new ArrayList<>();}else cell.append(c);}if(cell.length()>0||!row.isEmpty()){row.add(cell.toString());out.add(row);}return out;}}
}
